BUN_NAME = 'Космос'
BUN_PRICE = 20.00

INGREDIENT_NAME = 'Картошка'
INGREDIENT_TYPE = 'Начинка'
INGREDIENT_PRICE = 25

INGREDIENT_NAME_NEXT = 'Пармеджано'
INGREDIENT_TYPE_NEXT = 'Соус'
INGREDIENT_PRICE_NEXT = 50
